//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VDService
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEEDBACK
    {
        public int ID_FEEDBACK { get; set; }
        public int ID_USER { get; set; }
        public int ID_BOOK { get; set; }
        public string FEEDBACK1 { get; set; }
        public float RATING { get; set; }
        public System.DateTime DATE { get; set; }
    
        public virtual BOOKS BOOKS { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
