//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VDService
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAINT
    {
        public int ID_PAINT { get; set; }
        public int ID_ARTIST { get; set; }
        public int ID_BOOK { get; set; }
        public int ID_USER_ADD { get; set; }
        public string LINK { get; set; }
        public System.DateTime DATA { get; set; }
    
        public virtual ARTIST ARTIST { get; set; }
        public virtual BOOKS BOOKS { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
