//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VDService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBSCRIPTION
    {
        public int ID_USER { get; set; }
        public int ID_AUTHOR { get; set; }
        public System.DateTime DATA_SUB { get; set; }
    
        public virtual AUTHORS AUTHORS { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
