//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VDService
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_BOOKMARKS
    {
        public int ID_USER { get; set; }
        public int ID_BOOK { get; set; }
        public string STATUS_READING { get; set; }
        public bool PRESENCE { get; set; }
        public Nullable<System.DateTime> DATA_READING { get; set; }
        public System.DateTime DATA_ADD { get; set; }
        public int MARKS { get; set; }
    
        public virtual BOOKS BOOKS { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
